name: static webhosting
on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: cloning repository
        uses: actions/checkout@v4

      - name: copy website files to nginx
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          souce: "./*"
          target: "/tmp/website"

      - name: deploy into website
        uses: appleboy/ssh-action@v1
        with:
           host: ${{ secrets.IP }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.PRIVATE_KEY }}
           script: |
             sudo cp -r /tmp/website/* /var/nginx/html
             sudo systemctl reload nginx
             

      
